package com.nudgery.shared.util

val STOP_WORDS: Set<String> = setOf(
    // Articles
    "a", "an", "the",

    // Personal pronouns
    "i", "me", "my", "myself",
    "we", "us", "our", "ours", "ourselves",
    "you", "your", "yours", "yourself", "yourselves",
    "he", "him", "his", "himself",
    "she", "her", "hers", "herself",
    "it", "its", "itself",
    "they", "them", "their", "theirs", "themselves",

    // Demonstrative & relative pronouns
    "this", "that", "these", "those",
    "who", "whom", "whose", "which",

    // Indefinite pronouns & determiners
    "all", "any", "both", "each", "every", "few", "many", "more", "most",
    "no", "nor", "not", "other", "same", "some", "such",
    "someone", "anyone", "everyone", "nobody", "somebody", "anybody", "everybody",
    "something", "anything", "everything", "nothing",
    "somewhere", "anywhere", "everywhere", "nowhere",

    // Prepositions
    "about", "above", "across", "after", "against", "along", "among",
    "around", "as", "at", "before", "behind", "below", "beneath", "beside",
    "between", "beyond", "by", "despite", "down", "during", "except",
    "for", "from", "in", "inside", "into", "like", "near", "of", "off",
    "on", "onto", "out", "outside", "over", "past", "per", "through",
    "throughout", "to", "toward", "towards", "under", "underneath", "until",
    "unto", "up", "upon", "via", "with", "within", "without",

    // Conjunctions
    "although", "and", "because", "before", "but", "either",
    "even", "for", "however", "if", "neither", "or", "since", "so",
    "than", "that", "though", "unless", "until", "when", "whenever", "where",
    "whereas", "wherever", "whether", "while", "yet",

    // Auxiliary & modal verbs
    "am", "are", "be", "been", "being", "can", "could", "dare", "did",
    "do", "does", "had", "has", "have", "having", "is", "may", "might",
    "must", "need", "ought", "shall", "should", "was", "were", "will", "would",

    // Common high-frequency verbs
    "appear", "appeared", "appears",
    "ask", "asked", "asks",
    "become", "became", "becomes",
    "begin", "began", "begun", "begins",
    "bring", "brought", "brings",
    "call", "called", "calls",
    "close", "closed", "closes",
    "come", "came", "comes",
    "end", "ended", "ends",
    "fall", "fell", "falls",
    "feel", "felt", "feels",
    "find", "found", "finds",
    "follow", "followed", "follows",
    "get", "got", "gotten", "gets",
    "give", "gave", "given", "gives",
    "go", "went", "gone", "goes",
    "happen", "happened", "happens",
    "hear", "heard", "hears",
    "hold", "held", "holds",
    "keep", "kept", "keeps",
    "know", "knew", "known", "knows",
    "leave", "left", "leaves",
    "let", "lets",
    "look", "looked", "looks",
    "lose", "lost", "loses",
    "make", "made", "makes",
    "meet", "met", "meets",
    "move", "moved", "moves",
    "open", "opened", "opens",
    "pass", "passed", "passes",
    "play", "played", "plays",
    "pull", "pulled", "pulls",
    "put", "puts",
    "reach", "reached", "reaches",
    "remain", "remained", "remains",
    "return", "returned", "returns",
    "run", "ran", "runs",
    "say", "said", "says",
    "see", "saw", "seen", "sees",
    "seem", "seemed", "seems",
    "send", "sent", "sends",
    "set", "sets",
    "show", "showed", "shown", "shows",
    "sit", "sat", "sits",
    "stand", "stood", "stands",
    "start", "started", "starts",
    "stay", "stayed", "stays",
    "stop", "stopped", "stops",
    "take", "took", "taken", "takes",
    "tell", "told", "tells",
    "think", "thought", "thinks",
    "try", "tried", "tries",
    "turn", "turned", "turns",
    "use", "used", "uses",
    "wait", "waited", "waits",
    "walk", "walked", "walks",
    "want", "wanted", "wants",
    "watch", "watched", "watches",

    // Common adverbs
    "again", "already", "also", "always", "away", "back", "certainly",
    "definitely", "down", "ever", "finally", "further", "here", "how",
    "just", "maybe", "much", "never", "now", "often", "only", "perhaps",
    "probably", "quite", "rather", "really", "since", "slowly", "somehow",
    "soon", "still", "suddenly", "then", "there", "today", "tomorrow", "too",
    "twice", "usually", "very", "well", "when", "where", "why", "yesterday",

    // Common contractions (apostrophe is preserved in the middle by tokenization)
    "aren't", "can't", "couldn't", "didn't", "doesn't", "don't",
    "hadn't", "hasn't", "haven't",
    "he'd", "he'll", "he's",
    "here's", "how's",
    "i'd", "i'll", "i'm", "i've",
    "isn't", "it's",
    "let's",
    "she'd", "she'll", "she's",
    "shouldn't",
    "that'd", "that'll", "that's",
    "there'd", "there're", "there's",
    "they'd", "they'll", "they're", "they've",
    "wasn't", "we'd", "we'll", "we're", "we've", "weren't",
    "what'd", "what'll", "what's",
    "where's", "who'd", "who's",
    "won't", "wouldn't",
    "you'd", "you'll", "you're", "you've",
)
